# @format

name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t vicksemmanuel/x_ray_detection .
      - name: Publish image to docker hub
        run: docker push vicksemmanuel/x_ray_detection:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Clean up docker
        run: docker system prune -f
      - name: Pull image from docker hub
        run: docker pull vicksemmanuel/x_ray_detection:latest
      - name: Delete old container
        run: docker rm -f x_ray_detection-container
      - name: Run docker container
        run: docker run -d -p 80:8080 --name x_ray_detection-container vicksemmanuel/x_ray_detection
